site_name: BlackSky
theme: material
markdown_extensions:
  - admonition #MkDocs 警告框
  - footnotes #脚注
  - meta #自定义文章元数据
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - toc: # 大纲
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
   
palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式